//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string NumeroSerie { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> CodigoDeposito { get; set; }
        public Nullable<int> CodigoProveedor { get; set; }
    
        public virtual Deposito Deposito { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
